[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_URL = "https://gadget-zone-7r8e.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://gadget-zone-7r8e.onrender.com/api"

[context.deploy-preview.environment]
  VITE_API_URL = "https://gadget-zone-7r8e.onrender.com/api"
